version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.7.7-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      # https://github.com/dockerfile/rabbitmq/issues/22
      - RABBITMQ_NODENAME=rabbit@rabbitmq
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=12345
    volumes:
      # https://github.com/docker-library/rabbitmq/issues/171#issuecomment-323941561
      - /spring-cloud-dataflow-playground/rabbitmq/data/mnesia:/var/lib/rabbitmq/mnesia

  redis:
    image: redis:2.8
    expose:
      - "6379"

  dataflow-server:
    image: springcloud/spring-cloud-dataflow-server-local:1.6.3.RELEASE
    ports:
      - "9393:9393"
      - "9001-9011:9000-9010"
    environment:
      - spring.cloud.dataflow.applicationProperties.stream.spring.rabbitmq.host=rabbitmq
      - spring.cloud.dataflow.applicationProperties.stream.spring.rabbitmq.user=root
      - spring.cloud.dataflow.applicationProperties.stream.spring.rabbitmq.password=12345
      - spring.cloud.dataflow.applicationProperties.stream.spring.redis.host=redis
      - spring_redis_host=redis
    depends_on:
      - rabbitmq
      - redis

  app-import:
    image: alpine:3.7
    depends_on:
      - dataflow-server
    command: >
      /bin/sh -c "
        while ! nc -z dataflow-server 9393;
        do
          sleep 1;
        done;
        wget -qO- 'http://dataflow-server:9393/apps' --post-data='uri=http://bit.ly/Celsius-SR3-stream-applications-kafka-10-maven&force=true';
        echo 'Stream apps imported'
        wget -qO- 'http://dataflow-server:9393/apps' --post-data='uri=http://bit.ly/Clark-GA-task-applications-maven&force=true';
        echo 'Task apps imported'"

